# Generated by Django 5.2.5 on 2025-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0003_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
